### PR TITLE
fix values of expires and expires_at

### PR DESCRIPTION
**Pull request by chiu0602**

### CODE REVIEW

**Comment by chiu0602** [comment]
After applying the fix, error occurred in `else` block in `async jwt`. It indicates the fixed code able to fall into refresh token flow when token expired, but I don't know how to handle the code failed to refresh token.

**Comment by chiu0602** [comment]
It is NextAuth.js bug
https://github.com/nextauthjs/next-auth/issues/7558

**Comment by pintoderian** [comment]
> Es NextAuth.js bug [nextauthjs/next-auth#7558](https://github.com/nextauthjs/next-auth/issues/7558)

Hi, thanks for taking the time to review. From what you say, it seems that it would be better to wait for the error to be resolved before applying the corrections.

**Comment by chiu0602** [comment]
Thanks for your reply. As a workaround, do you know how to redirect the user to login page when token is found expired on `jwt` callback? Thanks!

**Comment by pintoderian** [comment]
I just improved the refresh token and this part was also corrected.

**Pull request closed without merging**
